### ISSUE TITLE
Perfomance improvment

### ISSUE THREAD

**Issue by 0xd34b33f** [tversteeg/emplace#58]
Now, most of the time is spent in git related operations. 
So i think, we need to rework this module.
Maybe make git operations async, or do not git pull on every command execution

**Comment by tversteeg** [comment]
Any suggestions for code paths and commands where to make it async and how?

**Comment by 0xd34b33f** [comment]
I see two ways: first -  create client server architecture. Server will be started with bash/zsh/*shrc , or with systemd/init. Server will periodic pull repo for changes, and client will be invoked on every catch.
Second - git pull only on clean, history and install commands, but this will create some troubles with synchronization of information on different devices. So we should create branches with device name and set key in config, which will represent time of how often should we synchronize it. Timestamp of last synchronization will be stored in some file.
Like this:
```
syncronization_period = Some(Instant)
```
Where is `none` is no synchronization.

**Comment by tversteeg** [comment]
I like the idea of the server but I think it's a bit overkill. I think it's better to spend some time improving the git calls like I've attempted for a bit in #57.

It shouldn't `git pull` on every command, only when you actually catch something, otherwise it's a bug. Maybe check if it's still bad enough using the refactor branch? I feel like it improved a bit.

**Comment by 0xd34b33f** [comment]
Yap, it's checking on catch, but it's spending near 10  seconds on checking, that git repo is in sync. If you're using emplace only on 1 device, it's redundant. 

> Maybe check if it's still bad enough using the refactor branch?  

I'l check it.
One more improvement - invoke catch only if process finished with zero exit code

**Comment by tversteeg** [comment]
> Yap, it's checking on catch, but it's spending near 10 seconds on checking, that git repo is in sync. If you're using emplace only on 1 device, it's redundant.

Maybe we can add a configurable option for that case? If you only use it on one machine with a dedicated repository for it it makes sense to never pull.

> One more improvement - invoke catch only if process finished with zero exit code

I thought I implemented this already but apparently it doesn't work consistently.

**Comment by 0xd34b33f** [comment]
But it works as it should :) First expression is true, and second is false. You are checking the first expression. If you want to test it properly, run something like `apt install test && false`

**Comment by 0xd34b33f** [comment]
Yap, we can create additional switch for it and create additional branch for every device, named with it's hostname. On install emplace'll clone all branches, read all the data, merge it & dedup.

**Comment by tversteeg** [comment]
> Yap, we can create additional switch for it and create additional branch for every device, named with it's hostname. On install emplace'll clone all branches, read all the data, merge it & dedup.

I think this idea sounds but good but in practice it's going to be very annoying to deal with the different merge conflicts from different branches. I would like to keep the git setup as simple as possible.

**Comment by 0xd34b33f** [comment]
Nono. It's much more easier. Clone repo with all branches. Read configs from every branch into memory. Merge vectors. Merge, using git is really hard for such task (:

**Comment by tversteeg** [comment]
It does add complexity for the user in determining the name of the branches. It's also less transparent when the configuration is spread out over multiple branches. And how is `emplace clean` implemented?

**Comment by 0xd34b33f** [comment]
I don't think, that having several branches makes it difficult. Moreover, I think, that most of  users will use 1 branch.
As I understand it wotkflow, you are deliting packages, intalled with previous `emplace install`. So on emplace install you will create  .installed _timestamp file in branch associated with the current hostname. And on clean you will read this file, delete related packages and remove the file.

**Comment by tversteeg** [comment]
I see what you mean, but the reason for this is that the `git pull` takes 10 seconds on your machine, which is valid. If that happens every catch then it's a bug. So when that bug is fixed and you only have to `git pull` when you're actually catching a proper package, which only happens when you install something. Is in that case the performance still a problem for you? How many seconds would be acceptable if it isn't?

**Comment by tversteeg** [comment]
@0xd34b33f are you still experiencing this problem after upgrading to 0.3?

**Comment by 0xd34b33f** [comment]
Sorry, I'm busy as hell :( I'm  going to create a pr with changes

**Comment by tversteeg** [comment]
No problem take your time, there's no rush :)

**Comment by 0xd34b33f** [comment]
Take a look at this [method](https://github.com/0xd34b33f/emplace/blob/cc5cd3aa267e60b751208fb723d1beb71752fdcb/src/catch.rs#L23) and this [method](https://github.com/0xd34b33f/emplace/blob/cc5cd3aa267e60b751208fb723d1beb71752fdcb/src/repo.rs#L71). It's written very clumsy, but you can find the idea behind it. This changes will require some api changes, so you should do them

**Comment by tversteeg** [comment]
I understand the changes, you don't want to pull after a catch, but I think this behavior is actually good to have. I also understand your point of view so how about adding a option to `emplace.toml` that allows you to choose the behavior?

**Comment by 0xd34b33f** [comment]
It's different thing. You don't need to pull repo, if local copy already has information, that command was  caught.

**Comment by tversteeg** [comment]
Yeah but the pull is to ensure that there will be no merge conflicts when the remote is updated.

**Comment by 0xd34b33f** [comment]
Look. You have information, that command was caught.
So, you're not going to do any changes to  repo because information is already here and because of this no merge conflicts can be present. Maybe I'm mistaken :)

**Comment by tversteeg** [comment]
Let me elaborate on it a bit more:

Say you have two computers, A at work and B at home, both are already configured to use emplace with the same repository.

When I'm at work on computer A, I find a nice package I want to store: `apt install peek`, this is pushed to the repository.
Then I go home on computer B and I'm doing something else, I find another nice package I want to store: `apt install inkscape`.

I haven't run `emplace install` yet in this situation. So what happens in the current situation when 'catch' does a `git pull` is that the `peek` package is pulled before I'm adding the `inkscape` package. But if 'catch' wouldn't have the `git pull` there would be a merge conflict because I'm trying to commit the list without `peek` locally while the remote has `inkscape`..

**Comment by 0xd34b33f** [comment]
Giving you an [example]( https://asciinema.org/a/8nGMa4JTUxtNMkXW8Uq1A5zKp).
You can avoid it, simply checking, that command is already in local file. No need to git pull. This will give you nothing. No potential conflicts, because you are not writing anything to file.  And if only  command is not presented in local storage, then you need to git pull.

**Comment by tversteeg** [comment]
I see, so that's a bit more nuanced than the thing I was talking about. There's still a small problem though, what if you already caught that command with emplace on another machine?

**Comment by 0xd34b33f** [comment]
Than no problem, nothing is found in cache, need to git pull and filter out, that it   is already caught

**Comment by tversteeg** [comment]
Ah yes that would work indeed. I'm okay with that :)
